### ISSUE TITLE
Cleanup directory tree

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/ESMA_cmake#206]
@amdasilva pointed out that the top directory of this repo has grown a bit messy.  A few judicious (well named) subdirectories should help considerably.   And maybe add something in the README about navigation of those directories?

**Comment by mathomp4** [comment]
This should be doable. I guess we usually only do:
```cmake
include(esma)
include(esma_cpack)
```
in the fixtures, so hiding should be pretty simple. (Fear is if I break UFS or GCHP. I guess that's a reason for an ESMA_cmake 4.0.0...
