### ISSUE TITLE
Convert set(VAR CACHE BOOL) to option()

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/ESMA_cmake#23]
Both `esma_check_if_debug.cmake` and `esma.cmake` have boolean cached options. It might be "cleaner" to change uses of:
```cmake
set (VAR ON CACHE BOOL "help text")
``` 
to use
```cmake
option (VAR "help text" ON)
```
per [this page](https://cliutils.gitlab.io/modern-cmake/chapters/basics/variables.html) it seems equivalent and more succinct. (Note [CMP0077](https://cmake.org/cmake/help/latest/policy/CMP0077.html#policy:CMP0077) so we should be careful to make sure override behaviors are what we want.)

**Comment by weiyuan-jiang** [comment]
There are many set command can be changed to option command. For example
#set (BUILD_SHARED_LIBS OFF)
option(BUILD_SHARED_LIBS "Build the shared library" OFF)

**Comment by tclune** [comment]
@weiyuan-jiang Note - this really only applies to variables that are _cached_.    Ordinary set() commands should not be changed.   OTOH, your example looks like one that probably should have been cached ...

I'll look at this some more in the morning.
