### ISSUE TITLE
New CMake Warning from CMake 3.17: CMP0068

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/ESMA_cmake#63]
When building GEOS, there is a new warning that CMake is spitting out:

```
CMake Deprecation Warning at @cmake/@ecbuild/cmake/ecbuild_policies.cmake:99 (cmake_policy):
  The OLD behavior for policy CMP0068 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  @cmake/@ecbuild/cmake/ecbuild_system.cmake:48 (include)
  @cmake/esma.cmake:16 (include)
  CMakeLists.txt:31 (include)
```
Per the [CMake docs on CMP0068](https://cmake.org/cmake/help/latest/policy/CMP0068.html):

> This policy was introduced in CMake version 3.9. CMake version 3.17.0 warns when the policy is not set and uses OLD behavior. Use the cmake_policy() command to set it to OLD or NEW explicitly.

As the traceback says, this is coming from ecbuild. Now, we already set some policies in the `CMakeLists.txt` of various/all fixtures, but we don't explicitly set 0068. 

I'm not sure what to set it to. I think ecbuild says use the OLD:
```cmake
# RPATH settings on macOS do not affect "install_name"
# FTM, keep old behavior -- need to test if new behavior impacts binaries in build directory
if( POLICY CMP0068 )
    cmake_policy( SET CMP0068 OLD )
endif()
```
And I'm not sure why that `cmake_policy()` call doesn't satisfy CMake. 

Still, maybe we should explicitly set the policy for 0068 in GEOS?

**Comment by mathomp4** [comment]
Interesting. The *only* way I seem to be able to suppress this warning is to edit `@ecbuild/cmake/ecbuild_policies.cmake` file directly. I tried setting:
```cmake
cmake_policy (SET CMP0068 NEW)
```
in the make `CMakeLists.txt` file and it didn't help

**Comment by mathomp4** [comment]
Note for @tclune, I decided to just go into `@ecbuild/cmake/ecbuild_policies.cmake` and hard code a `NEW` instead of `OLD` and the warning goes away. And the model seems to build and run identically on my laptop.

The question is, should I patch our fork of `@ecbuild` or do we live with the warning when we move to CMake 3.17 until we get a better idea of how to solve it from our code?

**Comment by tclune** [comment]
Have you looked at more recent ecbuild releases?   Perhaps they've dealt with this already?

I'm otherwise fine with patching our ecbuild fork.

**Comment by mathomp4** [comment]
It doesn't look like it. For now I'll patch and then I'll look at updating our branch to JSCDA's updates.
